package com.reuven.dynamodblocal.entities;

import com.reuven.dynamodblocal.dto.converters.LocalDateTimeConverter;
import com.reuven.dynamodblocal.dto.converters.UserMetadataConverter;
import com.reuven.dynamodblocal.utils.Constants;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.Objects;
import java.util.UUID;

import static com.reuven.dynamodblocal.utils.Constants.*;
//@DynamoDbBean
//public record UserMessages(@DynamoDbPartitionKey @DynamoDbAttribute("UserId") String userId, // מפתח Hash Key
//                           @DynamoDbSortKey @DynamoDbAttribute("CreatedTime") @DynamoDbConvertedBy(LocalDateTimeConverter.class) LocalDateTime createdTime,// Sort Key כ-String
//                           @DynamoDbAttribute("Message") String message) {
//    public UserMessages(String userId, String message) {
//        this(userId, LocalDateTime.now(ZoneOffset.UTC), message);
//    }
//
//    // Default constructor (Required)
//    public UserMessages() {
//        this(null, null, null);
//    }
//}

@DynamoDbBean
public class UserMessages {
    private String userId; // Partition Key
    private String messageUuid; // Sort Key
    private LocalDateTime createdTime; // Sort Key (stored as String in ISO-8601 format)
    private String message;
    private UserMetadata userMetadata;

    // Default constructor (Required)
    public UserMessages() {}

    public UserMessages(String userId, String message) {
        this(userId, message, null);
    }

    public UserMessages(String userId, String message, UserMetadata userMetadata) {
        this.userId = userId;
        this.createdTime = LocalDateTime.now(ZoneOffset.UTC); //.format(DateTimeFormatter.ISO_DATE_TIME);
        this.messageUuid = UUID.randomUUID().toString();
        this.message = message;
        this.userMetadata = userMetadata;
    }

    @DynamoDbPartitionKey
    @DynamoDbAttribute(USER_ID)
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDbSortKey
//    @DynamoDbAutoGeneratedUuid
    @DynamoDbAttribute(MESSAGE_UUID)
    public String getMessageUuid() {
        return messageUuid;
    }

    public void setMessageUuid(String messageUuid) {
        this.messageUuid = messageUuid;
    }

    @DynamoDbSecondarySortKey(indexNames = USER_MESSAGES_INDEX)
    @DynamoDbAttribute(CREATED_TIME)
    @DynamoDbConvertedBy(LocalDateTimeConverter.class)
    public LocalDateTime getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    @DynamoDbAttribute(MESSAGE)
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @DynamoDbAttribute(Constants.USER_METADATA)
    @DynamoDbConvertedBy(UserMetadataConverter.class)
    public UserMetadata getUserMetadata() {
        return userMetadata;
    }

    public void setUserMetadata(UserMetadata userMetadata) {
        this.userMetadata = userMetadata;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        UserMessages that = (UserMessages) o;
        return Objects.equals(userId, that.userId) && Objects.equals(messageUuid, that.messageUuid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId, messageUuid);
    }

    @Override
    public String toString() {
        return "UserMessages{" +
                "userId='" + userId + '\'' +
                ", messageUuid='" + messageUuid + '\'' +
                ", createdTime=" + createdTime +
                ", message='" + message + '\'' +
                '}';
    }
}
